In [1]:
import pandas as pd
import numpy as np

def process_buy_hold_trades(file_path: str):
    """
    End-to-end Buy-Hold strategy PnL computation.

    Logic
    -----
    1. Identify trades using:
       - Month gaps
       - Quantity changes
    2. Compute per-trade returns
    3. Compute compounded strategy return

    Returns
    -------
    bh_pivot : pd.DataFrame
        Trade-level details with buy, sell, PnL, dates
    strategy_return : float
        Compounded strategy return
    """

    # ----------------------------
    # Step 1: Read & prepare data
    # ----------------------------
    df = pd.read_excel(file_path)

    df["Date"] = pd.to_datetime(df["Date"])
    df = df.sort_values(["Ticker", "Date"])

    df["YearMonth"] = df["Date"].dt.to_period("M")

    df = df[["Ticker", "Date", "YearMonth", "Buy_Hold_Value", "Quantity"]]

    # ----------------------------
    # Step 2: Monthly snapshot
    # ----------------------------
    df_month = (
        df.drop_duplicates(subset=["Ticker", "YearMonth"])
          .sort_values(["Ticker", "YearMonth"])
    )

    # ----------------------------
    # Step 3: Trade ID logic
    # ----------------------------
    def get_trade_id(g):
        diff_months = g["YearMonth"].diff().apply(
            lambda x: x.n if pd.notna(x) else 1
        )

        new_trade = (
            diff_months.isna() |                # first row
            (diff_months > 1) |                 # month gap
            (g["Quantity"] != g["Quantity"].shift(1))  # quantity change
        )

        return new_trade.cumsum()

    df_month["trade_id"] = (
        df_month.groupby("Ticker", group_keys=False)
                .apply(get_trade_id)
    )

    # ----------------------------
    # Step 4: Merge trade_id back
    # ----------------------------
    df = df.merge(
        df_month[["Ticker", "YearMonth", "trade_id"]],
        on=["Ticker", "YearMonth"],
        how="left"
    )

    # ----------------------------
    # Step 5: Identify buy / sell
    # ----------------------------
    first_date = df.groupby(["Ticker", "trade_id"])["Date"].transform("min")
    last_date  = df.groupby(["Ticker", "trade_id"])["Date"].transform("max")

    df["Transaction"] = np.select(
        [
            df["Date"] == first_date,
            df["Date"] == last_date
        ],
        ["buy", "sell"],
        default=""
    )

    # ----------------------------
    # Step 6: Pivot to trade level
    # ----------------------------
    trades = df[df["Transaction"] != ""]

    bh_pivot = (
        trades.pivot_table(
            index=["Ticker", "trade_id"],
            columns="Transaction",
            values="Buy_Hold_Value",
            aggfunc="first"
        )
        .reset_index()
    )

    # ----------------------------
    # Step 7: Per-trade return
    # ----------------------------
    bh_pivot["Profit/Loss%"] = bh_pivot["sell"] / bh_pivot["buy"] - 1
    bh_pivot["Profit/Loss"] = bh_pivot["sell"] - bh_pivot["buy"]

    # ----------------------------
    # Step 8: Add Buy/Sell dates
    # ----------------------------
    buy_dates = trades[trades["Transaction"] == "buy"][
        ["Ticker", "trade_id", "Date"]
    ].rename(columns={"Date": "Buy Date"})

    sell_dates = trades[trades["Transaction"] == "sell"][
        ["Ticker", "trade_id", "Date"]
    ].rename(columns={"Date": "Sell Date"})

    bh_pivot = (
        bh_pivot.merge(buy_dates, on=["Ticker", "trade_id"])
                 .merge(sell_dates, on=["Ticker", "trade_id"])
    )

    # ----------------------------
    # Step 9: Strategy return (CRITICAL)
    # ----------------------------
    strategy_return = (1 + bh_pivot["Profit/Loss"]).prod() - 1

    return bh_pivot, strategy_return

#Absolute logic, if a stock remains for more than a month inside the portfolio without quantity change, the return shall be calculated for the whole period, eg 3 months

In [2]:
result = process_buy_hold_trades('Momentum_Maxfolio.xlsx')[0]
result

C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Roaming\Python\Python314\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])
C:\Users\anike\AppData\Local\Temp\ipykernel_23664\1455454763.py:62: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(get_trade_id)

,Ticker,trade_id,buy,sell,Profit/Loss%,Profit/Loss,Buy Date,Sell Date
0,ABCAPITAL,1,3.659772,3.676215,0.004493,0.016444,2025-12-01,2025-12-31
1,AIIL,1,3.750000,3.704489,-0.012136,-0.045511,2025-11-11,2025-11-28
2,ANANDRATHI,1,3.750000,3.511743,-0.063535,-0.238257,2025-11-11,2025-11-28
3,ANANDRATHI,2,3.692864,3.655636,-0.010081,-0.037228,2026-01-01,2026-01-22
4,AUBANK,1,3.661515,3.831011,0.046291,0.169497,2025-12-01,2025-12-31
5,CANBK,1,3.750000,4.035103,0.076028,0.285103,2025-11-11,2025-11-28
6,CANBK,2,3.697683,3.727889,0.008169,0.030207,2026-01-01,2026-01-22
7,CUMMINSIND,1,3.750000,3.433974,-0.084273,-0.316026,2025-11-11,2026-01-22
8,DELHIVERY,1,3.750000,3.715996,-0.009068,-0.034004,2025-11-11,2025-11-28
9,EICHERMOT,1,3.717375,3.817280,0.026875,0.099906,2025-12-01,2026-01-22
10,FORTIS,1,3.750000,3.492375,-0.068700,-0.257625,2025-11-11,2025-11-28
11,GLAND,1,3.750000,3.564445,-0.049481,-0.185555,2025-11-11,2025-11-28
12,GOLDBEES,1,25.000000,25.321909,0.012876,0.321909,2025-11-11,2025-11-28
13,GOLDBEES,2,15.498112,17.725821,0.143741,2.227708,2025-12-01,2026-01-22
14,GPIL,1,3.721142,3.506193,-0.057764,-0.214950,2026-01-01,2026-01-22
15,HBLENGINE,1,3.750000,2.759694,-0.264082,-0.990306,2025-11-11,2026-01-22
16,HEROMOTOCO,1,3.750000,3.919589,0.045224,0.169589,2025-11-11,2026-01-22
17,HINDALCO,1,3.750000,4.482756,0.195402,0.732756,2025-11-11,2026-01-22
18,HINDCOPPER,1,3.750000,3.409091,-0.090909,-0.340909,2025-11-11,2025-11-28
19,HYUNDAI,1,3.750000,3.702250,-0.012733,-0.047750,2025-11-11,2025-11-28
20,IIFL,1,3.750000,4.013176,0.070180,0.263176,2025-11-11,2025-11-28
21,IIFL,2,3.774272,3.718915,-0.014667,-0.055356,2026-01-01,2026-01-22
22,INDIANB,1,3.750000,3.617568,-0.035315,-0.132432,2025-11-11,2025-12-31
23,INTELLECT,1,3.750000,3.796410,0.012376,0.046410,2025-11-11,2025-11-28
24,JKTYRE,1,3.816802,3.896218,0.020807,0.079417,2026-01-01,2026-01-22
25,JSL,1,3.777908,3.426336,-0.093060,-0.351572,2026-01-01,2026-01-22
26,LAURUSLABS,1,3.750000,3.858806,0.029015,0.108806,2025-11-11,2026-01-22
27,LTF,1,3.750000,3.646416,-0.027622,-0.103584,2025-11-11,2026-01-22
28,LTIM,1,3.713614,3.659894,-0.014466,-0.053720,2025-12-01,2025-12-31
29,M&MFIN,1,3.640723,3.570462,-0.019299,-0.070261,2025-12-01,2026-01-22
30,MARUTI,1,3.725405,3.864266,0.037274,0.138861,2025-12-01,2025-12-31
31,MCX,1,3.729675,4.067940,0.090695,0.338264,2025-12-01,2025-12-31
32,MOGSEC,1,5.053121,5.037837,-0.003025,-0.015283,2025-12-01,2026-01-21
33,MUTHOOTFIN,1,3.745562,3.746152,0.000157,0.000590,2025-12-01,2025-12-31
34,NATIONALUM,1,3.733882,5.191766,0.390447,1.457884,2025-12-01,2026-01-22
35,NETWEB,1,3.750000,3.532859,-0.057904,-0.217141,2025-11-11,2025-11-28
36,NYKAA,1,3.646636,3.398847,-0.067950,-0.247790,2025-12-01,2026-01-22
37,PAYTM,1,3.750000,3.655167,-0.025289,-0.094833,2025-11-11,2025-12-31
38,POLYCAB,1,3.750000,3.730172,-0.005288,-0.019828,2025-11-11,2025-12-31
39,RADICO,1,3.663641,3.235340,-0.116906,-0.428301,2026-01-01,2026-01-22
40,SBIN,1,3.723387,3.965374,0.064991,0.241987,2026-01-01,2026-01-22
41,SHRIRAMFIN,1,3.801351,3.731080,-0.018486,-0.070271,2026-01-01,2026-01-22
42,SILVERBEES,1,5.369337,8.601082,0.601889,3.231746,2025-12-01,2026-01-22
43,SYRMA,1,3.647512,3.289064,-0.098272,-0.358448,2025-12-01,2025-12-31
44,VEDL,1,3.702992,4.224661,0.140878,0.521669,2026-01-01,2026-01-22

In [3]:
import numpy as np

mapping = {
    "SILVERBEES": "SILVER",
    "SILVER": "SILVER",
    "GOLDBEES": "GOLD",
    "MOGSEC": "DEBT"
}

result["Asset_Class"] = result["Ticker"].map(mapping).fillna("EQUITIES")
result

,Ticker,trade_id,buy,sell,Profit/Loss%,Profit/Loss,Buy Date,Sell Date,Asset_Class
0,ABCAPITAL,1,3.659772,3.676215,0.004493,0.016444,2025-12-01,2025-12-31,EQUITIES
1,AIIL,1,3.750000,3.704489,-0.012136,-0.045511,2025-11-11,2025-11-28,EQUITIES
2,ANANDRATHI,1,3.750000,3.511743,-0.063535,-0.238257,2025-11-11,2025-11-28,EQUITIES
3,ANANDRATHI,2,3.692864,3.655636,-0.010081,-0.037228,2026-01-01,2026-01-22,EQUITIES
4,AUBANK,1,3.661515,3.831011,0.046291,0.169497,2025-12-01,2025-12-31,EQUITIES
5,CANBK,1,3.750000,4.035103,0.076028,0.285103,2025-11-11,2025-11-28,EQUITIES
6,CANBK,2,3.697683,3.727889,0.008169,0.030207,2026-01-01,2026-01-22,EQUITIES
7,CUMMINSIND,1,3.750000,3.433974,-0.084273,-0.316026,2025-11-11,2026-01-22,EQUITIES
8,DELHIVERY,1,3.750000,3.715996,-0.009068,-0.034004,2025-11-11,2025-11-28,EQUITIES
9,EICHERMOT,1,3.717375,3.817280,0.026875,0.099906,2025-12-01,2026-01-22,EQUITIES
10,FORTIS,1,3.750000,3.492375,-0.068700,-0.257625,2025-11-11,2025-11-28,EQUITIES
11,GLAND,1,3.750000,3.564445,-0.049481,-0.185555,2025-11-11,2025-11-28,EQUITIES
12,GOLDBEES,1,25.000000,25.321909,0.012876,0.321909,2025-11-11,2025-11-28,GOLD
13,GOLDBEES,2,15.498112,17.725821,0.143741,2.227708,2025-12-01,2026-01-22,GOLD
14,GPIL,1,3.721142,3.506193,-0.057764,-0.214950,2026-01-01,2026-01-22,EQUITIES
15,HBLENGINE,1,3.750000,2.759694,-0.264082,-0.990306,2025-11-11,2026-01-22,EQUITIES
16,HEROMOTOCO,1,3.750000,3.919589,0.045224,0.169589,2025-11-11,2026-01-22,EQUITIES
17,HINDALCO,1,3.750000,4.482756,0.195402,0.732756,2025-11-11,2026-01-22,EQUITIES
18,HINDCOPPER,1,3.750000,3.409091,-0.090909,-0.340909,2025-11-11,2025-11-28,EQUITIES
19,HYUNDAI,1,3.750000,3.702250,-0.012733,-0.047750,2025-11-11,2025-11-28,EQUITIES
20,IIFL,1,3.750000,4.013176,0.070180,0.263176,2025-11-11,2025-11-28,EQUITIES
21,IIFL,2,3.774272,3.718915,-0.014667,-0.055356,2026-01-01,2026-01-22,EQUITIES
22,INDIANB,1,3.750000,3.617568,-0.035315,-0.132432,2025-11-11,2025-12-31,EQUITIES
23,INTELLECT,1,3.750000,3.796410,0.012376,0.046410,2025-11-11,2025-11-28,EQUITIES
24,JKTYRE,1,3.816802,3.896218,0.020807,0.079417,2026-01-01,2026-01-22,EQUITIES
25,JSL,1,3.777908,3.426336,-0.093060,-0.351572,2026-01-01,2026-01-22,EQUITIES
26,LAURUSLABS,1,3.750000,3.858806,0.029015,0.108806,2025-11-11,2026-01-22,EQUITIES
27,LTF,1,3.750000,3.646416,-0.027622,-0.103584,2025-11-11,2026-01-22,EQUITIES
28,LTIM,1,3.713614,3.659894,-0.014466,-0.053720,2025-12-01,2025-12-31,EQUITIES
29,M&MFIN,1,3.640723,3.570462,-0.019299,-0.070261,2025-12-01,2026-01-22,EQUITIES
30,MARUTI,1,3.725405,3.864266,0.037274,0.138861,2025-12-01,2025-12-31,EQUITIES
31,MCX,1,3.729675,4.067940,0.090695,0.338264,2025-12-01,2025-12-31,EQUITIES
32,MOGSEC,1,5.053121,5.037837,-0.003025,-0.015283,2025-12-01,2026-01-21,DEBT
33,MUTHOOTFIN,1,3.745562,3.746152,0.000157,0.000590,2025-12-01,2025-12-31,EQUITIES
34,NATIONALUM,1,3.733882,5.191766,0.390447,1.457884,2025-12-01,2026-01-22,EQUITIES
35,NETWEB,1,3.750000,3.532859,-0.057904,-0.217141,2025-11-11,2025-11-28,EQUITIES
36,NYKAA,1,3.646636,3.398847,-0.067950,-0.247790,2025-12-01,2026-01-22,EQUITIES
37,PAYTM,1,3.750000,3.655167,-0.025289,-0.094833,2025-11-11,2025-12-31,EQUITIES
38,POLYCAB,1,3.750000,3.730172,-0.005288,-0.019828,2025-11-11,2025-12-31,EQUITIES
39,RADICO,1,3.663641,3.235340,-0.116906,-0.428301,2026-01-01,2026-01-22,EQUITIES
40,SBIN,1,3.723387,3.965374,0.064991,0.241987,2026-01-01,2026-01-22,EQUITIES
41,SHRIRAMFIN,1,3.801351,3.731080,-0.018486,-0.070271,2026-01-01,2026-01-22,EQUITIES
42,SILVERBEES,1,5.369337,8.601082,0.601889,3.231746,2025-12-01,2026-01-22,SILVER
43,SYRMA,1,3.647512,3.289064,-0.098272,-0.358448,2025-12-01,2025-12-31,EQUITIES
44,VEDL,1,3.702992,4.224661,0.140878,0.521669,2026-01-01,2026-01-22,EQUITIES

In [4]:
(result.groupby("Asset_Class")["Profit/Loss"].sum() / 100).reset_index()

#copy paste values from here to google sheets

  Asset_Class  Profit/Loss
0        DEBT    -0.000153
1    EQUITIES    -0.002111
2        GOLD     0.025496
3      SILVER     0.032317

In [5]:
result.to_excel('PnL_Momentum_Maxfolio.xlsx', index=False)