In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_excel("Trials\\Nifty_500_2025_Apr_20_stocks_results_GoldSilverDebt_buy&hold_returns.xlsx")
data

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Initial_Allocation,Selection_Date,Buy_Hold_Value,Buy_Price,Quantity,Real_Rank,Total_Portfolio_Value,Hedge_Segment,Demerger_Entity
0,2023-04-03,154.00,154.90,152.00,153.80,2347046.0,0.0,ABCAPITAL,-0.001299,3.750000,2023-04-01,3.745130,153.80,0.024382,11.0,100.451652,NaN,NaN
1,2023-04-03,203.50,205.50,201.55,202.55,225128.0,0.0,ANANDRATHI,-0.004668,3.750000,2023-04-01,3.732494,202.55,0.018514,15.0,100.451652,NaN,NaN
2,2023-04-03,123.75,128.00,122.50,125.65,2365577.0,0.0,ANANTRAJ,0.015354,3.750000,2023-04-01,3.807576,125.65,0.029845,19.0,100.451652,NaN,NaN
3,2023-04-03,169.10,170.25,168.10,169.20,16659059.0,0.0,BANKBARODA,0.000591,3.750000,2023-04-01,3.752218,169.20,0.022163,7.0,100.451652,NaN,NaN
4,2023-04-03,75.00,76.45,74.10,75.95,8102076.0,0.0,BANKINDIA,0.012667,3.750000,2023-04-01,3.797500,75.95,0.049375,3.0,100.451652,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17697,2026-07-31,77.30,NaN,NaN,77.27,NaN,NaN,NEXT50IETF,0.010065,13.815925,2026-07-01,14.137949,76.01,0.181765,NaN,269.968329,2026-07_onward,NaN
17698,2026-07-31,27.50,NaN,NaN,27.21,NaN,NaN,PHARMABEES,0.004430,13.000837,2026-07-01,13.584976,25.83,0.503323,NaN,269.968329,2026-07_onward,NaN
17699,2026-07-31,2600.00,2638.00,2600.00,2628.30,119710.0,0.0,RRKABEL,0.025798,10.512529,2026-07-01,11.417388,2381.70,0.004414,9.0,269.968329,NaN,NaN
17700,2026-07-31,1380.50,1398.00,1363.10,1397.50,441070.0,0.0,SYRMA,0.014298,10.512529,2026-07-01,10.454180,1421.60,0.007395,3.0,269.968329,NaN,NaN
17701,2026-07-31,1668.40,1671.00,1657.10,1659.70,42277.0,0.0,WELCORP,0.002840,10.512529,2026-07-01,11.402943,1477.60,0.007115,4.0,269.968329,NaN,NaN

In [3]:
# max_date_tickers = data[(data['Date'] == '2025-12-31')]
# max_date_tickers
max_date_tickers = data[(data['Date'] == data['Date'].max())]
max_date_tickers

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Initial_Allocation,Selection_Date,Buy_Hold_Value,Buy_Price,Quantity,Real_Rank,Total_Portfolio_Value,Hedge_Segment,Demerger_Entity
17678,2026-07-31,7350.50,7485.00,7350.50,7421.50,91271.0,0.0,ABB,0.017829,8.948935,2026-07-01,9.445957,6937.00,0.001278,14.0,269.968329,NaN,NaN
17679,2026-07-31,1012.00,1016.40,1004.40,1016.40,12338.0,0.0,ABSLAMC,0.007534,9.356668,2026-07-01,8.236007,1144.60,0.008458,7.0,269.968329,NaN,NaN
17680,2026-07-31,3225.00,3232.90,3140.00,3160.00,75652.0,0.0,ACUTAAS,-0.022821,9.570275,2026-07-01,8.576390,3567.50,0.002856,1.0,269.968329,NaN,NaN
17681,2026-07-31,1247.00,1267.00,1237.00,1250.70,731625.0,0.0,ATHERENERG,0.007897,10.512529,2026-07-01,11.523242,1130.40,0.009300,19.0,269.968329,NaN,NaN
17682,2026-07-31,173.40,175.10,173.28,174.23,1300920.0,0.0,BANDHANBNK,0.008742,10.512529,2026-07-01,8.969627,205.04,0.051271,18.0,269.968329,NaN,NaN
17683,2026-07-31,2164.70,2199.10,2161.50,2194.10,118536.0,0.0,BHARATFORG,0.013582,10.931344,2026-07-01,11.186261,2108.80,0.005046,6.0,269.968329,NaN,NaN
17684,2026-07-31,406.00,412.35,406.00,409.95,1439407.0,0.0,BHEL,0.017246,10.792096,2026-07-01,10.683941,413.95,0.024537,11.0,269.968329,NaN,NaN
17685,2026-07-31,3538.50,3585.00,3517.00,3556.50,462125.0,0.0,BSE,0.007421,11.233623,2026-07-01,10.335363,3944.10,0.002848,5.0,269.968329,NaN,NaN
17686,2026-07-31,3259.90,3370.10,3259.90,3366.70,41099.0,0.0,CPPLUS,0.032793,10.512529,2026-07-01,9.672733,3572.30,0.002943,13.0,269.968329,NaN,NaN
17687,2026-07-31,77.51,NaN,NaN,78.25,NaN,NaN,DEFENCE,0.014916,12.652555,2026-07-01,12.406798,79.80,0.158553,NaN,269.968329,2026-07_onward,NaN
17688,2026-07-31,310.00,315.70,307.60,313.85,341029.0,0.0,EMMVEE,0.020816,8.974957,2026-07-01,8.212216,351.95,0.028370,2.0,269.968329,NaN,NaN
17689,2026-07-31,973.00,996.90,973.00,995.70,47683.0,0.0,FINCABLES,0.023330,10.512529,2026-07-01,8.941846,1144.50,0.009185,15.0,269.968329,NaN,NaN
17690,2026-07-31,4350.00,4410.00,4321.20,4350.70,420573.0,0.0,GVT&D,0.035314,10.164707,2026-07-01,8.944901,4895.70,0.002062,10.0,269.968329,NaN,NaN
17691,2026-07-31,763.60,781.90,763.00,774.85,912434.0,0.0,HSCL,0.018869,9.695147,2026-07-01,11.060490,645.55,0.014289,12.0,269.968329,NaN,NaN
17692,2026-07-31,154.40,156.96,153.20,156.40,1238268.0,0.0,J&KBANK,0.017302,10.512529,2026-07-01,10.586308,156.20,0.067302,16.0,269.968329,NaN,NaN
17693,2026-07-31,255.60,257.90,254.90,256.15,55712.0,0.0,JINDALSAW,0.007275,10.512529,2026-07-01,10.303364,260.25,0.040394,20.0,269.968329,NaN,NaN
17694,2026-07-31,2173.00,2206.70,2145.00,2194.80,64787.0,0.0,KIRLOSENG,0.029022,12.857205,2026-07-01,11.936968,2341.10,0.005368,17.0,269.968329,NaN,NaN
17695,2026-07-31,115.27,NaN,NaN,115.29,NaN,NaN,LIQUIDCASE,0.000434,27.141034,2026-07-01,27.266381,114.79,0.236441,NaN,269.968329,2026-07_onward,NaN
17696,2026-07-31,79.80,80.20,79.44,79.58,1199199.0,0.0,MAHABANK,0.004037,12.274078,2026-07-01,10.682099,91.20,0.131751,8.0,269.968329,NaN,NaN
17697,2026-07-31,77.30,NaN,NaN,77.27,NaN,NaN,NEXT50IETF,0.010065,13.815925,2026-07-01,14.137949,76.01,0.181765,NaN,269.968329,2026-07_onward,NaN
17698,2026-07-31,27.50,NaN,NaN,27.21,NaN,NaN,PHARMABEES,0.004430,13.000837,2026-07-01,13.584976,25.83,0.503323,NaN,269.968329,2026-07_onward,NaN
17699,2026-07-31,2600.00,2638.00,2600.00,2628.30,119710.0,0.0,RRKABEL,0.025798,10.512529,2026-07-01,11.417388,2381.70,0.004414,9.0,269.968329,NaN,NaN
17700,2026-07-31,1380.50,1398.00,1363.10,1397.50,441070.0,0.0,SYRMA,0.014298,10.512529,2026-07-01,10.454180,1421.60,0.007395,3.0,269.968329,NaN,NaN
17701,2026-07-31,1668.40,1671.00,1657.10,1659.70,42277.0,0.0,WELCORP,0.002840,10.512529,2026-07-01,11.402943,1477.60,0.007115,4.0,269.968329,NaN,NaN

In [4]:
total_value = max_date_tickers['Buy_Hold_Value'].sum()

# Calculate weights
max_date_tickers['Weight'] = max_date_tickers['Buy_Hold_Value'] / total_value

# Format as percentage (optional)
max_date_tickers['Weight_Percent'] = max_date_tickers['Weight']

max_date_tickers

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Initial_Allocation,Selection_Date,Buy_Hold_Value,Buy_Price,Quantity,Real_Rank,Total_Portfolio_Value,Hedge_Segment,Demerger_Entity,Weight,Weight_Percent
17678,2026-07-31,7350.50,7485.00,7350.50,7421.50,91271.0,0.0,ABB,0.017829,8.948935,2026-07-01,9.445957,6937.00,0.001278,14.0,269.968329,NaN,NaN,0.034989,0.034989
17679,2026-07-31,1012.00,1016.40,1004.40,1016.40,12338.0,0.0,ABSLAMC,0.007534,9.356668,2026-07-01,8.236007,1144.60,0.008458,7.0,269.968329,NaN,NaN,0.030507,0.030507
17680,2026-07-31,3225.00,3232.90,3140.00,3160.00,75652.0,0.0,ACUTAAS,-0.022821,9.570275,2026-07-01,8.576390,3567.50,0.002856,1.0,269.968329,NaN,NaN,0.031768,0.031768
17681,2026-07-31,1247.00,1267.00,1237.00,1250.70,731625.0,0.0,ATHERENERG,0.007897,10.512529,2026-07-01,11.523242,1130.40,0.009300,19.0,269.968329,NaN,NaN,0.042684,0.042684
17682,2026-07-31,173.40,175.10,173.28,174.23,1300920.0,0.0,BANDHANBNK,0.008742,10.512529,2026-07-01,8.969627,205.04,0.051271,18.0,269.968329,NaN,NaN,0.033225,0.033225
17683,2026-07-31,2164.70,2199.10,2161.50,2194.10,118536.0,0.0,BHARATFORG,0.013582,10.931344,2026-07-01,11.186261,2108.80,0.005046,6.0,269.968329,NaN,NaN,0.041435,0.041435
17684,2026-07-31,406.00,412.35,406.00,409.95,1439407.0,0.0,BHEL,0.017246,10.792096,2026-07-01,10.683941,413.95,0.024537,11.0,269.968329,NaN,NaN,0.039575,0.039575
17685,2026-07-31,3538.50,3585.00,3517.00,3556.50,462125.0,0.0,BSE,0.007421,11.233623,2026-07-01,10.335363,3944.10,0.002848,5.0,269.968329,NaN,NaN,0.038284,0.038284
17686,2026-07-31,3259.90,3370.10,3259.90,3366.70,41099.0,0.0,CPPLUS,0.032793,10.512529,2026-07-01,9.672733,3572.30,0.002943,13.0,269.968329,NaN,NaN,0.035829,0.035829
17687,2026-07-31,77.51,NaN,NaN,78.25,NaN,NaN,DEFENCE,0.014916,12.652555,2026-07-01,12.406798,79.80,0.158553,NaN,269.968329,2026-07_onward,NaN,0.045956,0.045956
17688,2026-07-31,310.00,315.70,307.60,313.85,341029.0,0.0,EMMVEE,0.020816,8.974957,2026-07-01,8.212216,351.95,0.028370,2.0,269.968329,NaN,NaN,0.030419,0.030419
17689,2026-07-31,973.00,996.90,973.00,995.70,47683.0,0.0,FINCABLES,0.023330,10.512529,2026-07-01,8.941846,1144.50,0.009185,15.0,269.968329,NaN,NaN,0.033122,0.033122
17690,2026-07-31,4350.00,4410.00,4321.20,4350.70,420573.0,0.0,GVT&D,0.035314,10.164707,2026-07-01,8.944901,4895.70,0.002062,10.0,269.968329,NaN,NaN,0.033133,0.033133
17691,2026-07-31,763.60,781.90,763.00,774.85,912434.0,0.0,HSCL,0.018869,9.695147,2026-07-01,11.060490,645.55,0.014289,12.0,269.968329,NaN,NaN,0.040970,0.040970
17692,2026-07-31,154.40,156.96,153.20,156.40,1238268.0,0.0,J&KBANK,0.017302,10.512529,2026-07-01,10.586308,156.20,0.067302,16.0,269.968329,NaN,NaN,0.039213,0.039213
17693,2026-07-31,255.60,257.90,254.90,256.15,55712.0,0.0,JINDALSAW,0.007275,10.512529,2026-07-01,10.303364,260.25,0.040394,20.0,269.968329,NaN,NaN,0.038165,0.038165
17694,2026-07-31,2173.00,2206.70,2145.00,2194.80,64787.0,0.0,KIRLOSENG,0.029022,12.857205,2026-07-01,11.936968,2341.10,0.005368,17.0,269.968329,NaN,NaN,0.044216,0.044216
17695,2026-07-31,115.27,NaN,NaN,115.29,NaN,NaN,LIQUIDCASE,0.000434,27.141034,2026-07-01,27.266381,114.79,0.236441,NaN,269.968329,2026-07_onward,NaN,0.100998,0.100998
17696,2026-07-31,79.80,80.20,79.44,79.58,1199199.0,0.0,MAHABANK,0.004037,12.274078,2026-07-01,10.682099,91.20,0.131751,8.0,269.968329,NaN,NaN,0.039568,0.039568
17697,2026-07-31,77.30,NaN,NaN,77.27,NaN,NaN,NEXT50IETF,0.010065,13.815925,2026-07-01,14.137949,76.01,0.181765,NaN,269.968329,2026-07_onward,NaN,0.052369,0.052369
17698,2026-07-31,27.50,NaN,NaN,27.21,NaN,NaN,PHARMABEES,0.004430,13.000837,2026-07-01,13.584976,25.83,0.503323,NaN,269.968329,2026-07_onward,NaN,0.050321,0.050321
17699,2026-07-31,2600.00,2638.00,2600.00,2628.30,119710.0,0.0,RRKABEL,0.025798,10.512529,2026-07-01,11.417388,2381.70,0.004414,9.0,269.968329,NaN,NaN,0.042292,0.042292
17700,2026-07-31,1380.50,1398.00,1363.10,1397.50,441070.0,0.0,SYRMA,0.014298,10.512529,2026-07-01,10.454180,1421.60,0.007395,3.0,269.968329,NaN,NaN,0.038724,0.038724
17701,2026-07-31,1668.40,1671.00,1657.10,1659.70,42277.0,0.0,WELCORP,0.002840,10.512529,2026-07-01,11.402943,1477.60,0.007115,4.0,269.968329,NaN,NaN,0.042238,0.042238

In [5]:
# Convert to dictionary
weights = dict(zip(max_date_tickers['Ticker'], max_date_tickers['Weight']))

weights

{'ABB': 0.034989129400632375,
 'ABSLAMC': 0.030507306936188788,
 'ACUTAAS': 0.03176813522719838,
 'ATHERENERG': 0.04268368228452352,
 'BANDHANBNK': 0.03322473854374172,
 'BHARATFORG': 0.04143545645636298,
 'BHEL': 0.0395747929406967,
 'BSE': 0.03828361446328757,
 'CPPLUS': 0.03582913988851138,
 'DEFENCE': 0.045956493329513126,
 'EMMVEE': 0.030419183813279863,
 'FINCABLES': 0.033121832799600986,
 'GVT&D': 0.03313315083666929,
 'HSCL': 0.040969582837156474,
 'J&KBANK': 0.03921314742778596,
 'JINDALSAW': 0.038165084557593376,
 'KIRLOSENG': 0.044216180098836835,
 'LIQUIDCASE': 0.10099844240340948,
 'MAHABANK': 0.03956797014941002,
 'NEXT50IETF': 0.05236891760174743,
 'PHARMABEES': 0.050320630075409954,
 'RRKABEL': 0.042291583084163566,
 'SYRMA': 0.03872372644169546,
 'WELCORP': 0.04223807840258489}

In [6]:
tickers = list(max_date_tickers['Ticker'].unique()) + ['NIFTY 500']
# tickers = [
#     "ABCAPITAL",
#     "AIIL",
#     "BOSCHLTD",
#     "DATAPATTNS",
#     "DELHIVERY",
#     "ETERNAL",
#     "GOLDBEES",
#     "GVT&D",
#     "HBLENGINE",
#     "HEROMOTOCO",
#     "HINDCOPPER",
#     "HYUNDAI",
#     "IIFL",
#     "INTELLECT",
#     "LAURUSLABS",
#     "LTF",
#     "MFSL",
#     "NETWEB",
#     "POLYCAB",
#     "SYRMA",
#     "TATAINVEST",
#     "NIFTY 500"
# ]

# tickers

In [7]:
len(tickers)

25

In [8]:

import time
import logging
import pandas as pd
from truedata import TD_hist

def fetch_truedata_history(
    ticker_list: list,
    duration: str = '1 Y',
    bar_size: str = 'EOD',
    sleep_time: float = 0.1
) -> tuple[pd.DataFrame, list]:
    """
    Fetches historical data from TrueData for a list of tickers.

    Parameters
    ----------
    username : str
        TrueData username.
    password : str
        TrueData password.
    ticker_list : list
        List of ticker symbols to fetch data for.
    duration : str, optional
        Duration of data (e.g., '1 Y', '25 Y', etc.). Default is '1 Y'.
    bar_size : str, optional
        Bar size for data ('EOD', 'WEEK', etc.). Default is 'EOD'.
    sleep_time : float, optional
        Delay between API calls to avoid throttling. Default is 0.2 seconds.

    Returns
    -------
    final_df : pd.DataFrame
        Combined DataFrame of all tickers' historical data.
    error_list : list
        List of tickers that failed to fetch.
    """
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    username =  'tdwsf695'
    password = 'ocean@695'
    # username =  'td105'
    # password = 'sharma@105'
    # Initialize connection
    td_hist = TD_hist(username, password)
    df_list = []
    error_list = []
    for ticker in ticker_list:
        try:
            df = td_hist.get_historic_data([ticker], duration=duration, bar_size=bar_size)

            df['Ticker'] = ticker
            df = df.rename(columns={
                'timestamp': 'Date',
                'high': 'High',
                'low': 'Low',
                'close': 'Close',
                'open': 'Open'
            })

            df_list.append(df)
            logging.info(f"Fetched data for {ticker} ({len(df)} rows).")
            time.sleep(sleep_time)

        except Exception as e:
            logging.error(f"Failed to fetch data for {ticker}: {e}")
            error_list.append(ticker)

    final_df = pd.concat(df_list, ignore_index=True) if df_list else pd.DataFrame()
    return final_df, error_list

In [9]:
ticker_data = fetch_truedata_history(
        ticker_list = tickers,
        duration = '2 Y',
        bar_size = 'EOD',
        sleep_time= 0.1
    )[0][['Ticker','Date', 'Close']]
ticker_data

(2026-07-31 09:49:57,542) WARNING :: Connected successfully to TrueData Historical Data Service...  (PID:28996 Thread:28040)
2026-07-31 09:49:57,542 - WARNING - Connected successfully to TrueData Historical Data Service...
2026-07-31 09:49:58,007 - INFO - Fetched data for ABB (497 rows).
2026-07-31 09:49:58,482 - INFO - Fetched data for ABSLAMC (497 rows).
2026-07-31 09:49:58,967 - INFO - Fetched data for ACUTAAS (497 rows).
2026-07-31 09:49:59,445 - INFO - Fetched data for ATHERENERG (309 rows).
2026-07-31 09:49:59,985 - INFO - Fetched data for BANDHANBNK (497 rows).
2026-07-31 09:50:00,508 - INFO - Fetched data for BHARATFORG (497 rows).
2026-07-31 09:50:01,019 - INFO - Fetched data for BHEL (497 rows).
2026-07-31 09:50:01,574 - INFO - Fetched data for BSE (497 rows).
2026-07-31 09:50:02,096 - INFO - Fetched data for CPPLUS (244 rows).
2026-07-31 09:50:02,749 - INFO - Fetched data for DEFENCE (109 rows).
2026-07-31 09:50:03,257 - INFO - Fetched data for EMMVEE (174 rows).
2026-07-31 09:50:03,801 - INFO - Fetched data for FINCABLES (497 rows).
2026-07-31 09:50:04,316 - INFO - Fetched data for GVT&D (497 rows).
2026-07-31 09:50:04,910 - INFO - Fetched data for HSCL (497 rows).
2026-07-31 09:50:05,417 - INFO - Fetched data for J&KBANK (497 rows).
2026-07-31 09:50:05,960 - INFO - Fetched data for JINDALSAW (497 rows).
2026-07-31 09:50:06,463 - INFO - Fetched data for KIRLOSENG (497 rows).
2026-07-31 09:50:06,980 - INFO - Fetched data for LIQUIDCASE (497 rows).
2026-07-31 09:50:07,484 - INFO - Fetched data for MAHABANK (497 rows).
2026-07-31 09:50:07,985 - INFO - Fetched data for NEXT50IETF (497 rows).
2026-07-31 09:50:08,477 - INFO - Fetched data for PHARMABEES (497 rows).
2026-07-31 09:50:08,945 - INFO - Fetched data for RRKABEL (497 rows).
2026-07-31 09:50:09,417 - INFO - Fetched data for SYRMA (497 rows).
2026-07-31 09:50:09,901 - INFO - Fetched data for WELCORP (497 rows).
2026-07-31 09:50:10,382 - INFO - Fetched data for NIFTY 500 (497 rows).

          Ticker       Date     Close
0            ABB 2024-07-31   7896.85
1            ABB 2024-08-01   7769.80
2            ABB 2024-08-02   7578.80
3            ABB 2024-08-05   7465.70
4            ABB 2024-08-06   7465.70
...          ...        ...       ...
11268  NIFTY 500 2026-07-27  23153.10
11269  NIFTY 500 2026-07-28  23114.90
11270  NIFTY 500 2026-07-29  23352.60
11271  NIFTY 500 2026-07-30  23353.55
11272  NIFTY 500 2026-07-31  23438.95

[11273 rows x 3 columns]

In [10]:
ticker_data[ticker_data.duplicated(subset=['Ticker', 'Date'])]

Empty DataFrame
Columns: [Ticker, Date, Close]
Index: []

In [11]:
ticker_data = ticker_data.drop_duplicates(subset=['Ticker', 'Date'])

In [12]:
# ticker_data[ticker_data['Ticker'] == 'MOGSEC'].to_excel('MOGSEC.xlsx', index=False)

In [13]:
ticker_data.pivot(index="Date", columns="Ticker", values="Close").sort_index()

Ticker,ABB,ABSLAMC,ACUTAAS,ATHERENERG,BANDHANBNK,BHARATFORG,BHEL,BSE,CPPLUS,DEFENCE,...,JINDALSAW,KIRLOSENG,LIQUIDCASE,MAHABANK,NEXT50IETF,NIFTY 500,PHARMABEES,RRKABEL,SYRMA,WELCORP
Date,,,,,,,,,,,,,,,,,,,,,
2024-07-31,7896.85,706.55,668.95,NaN,218.08,1733.50,315.25,852.15,NaN,NaN,...,324.15,1234.20,103.52,66.94,77.65,23530.80,22.18,1795.05,494.50,640.70
2024-08-01,7769.80,693.70,675.05,NaN,213.71,1717.55,308.50,881.10,NaN,NaN,...,323.60,1199.05,103.54,66.11,77.55,23506.60,22.19,1740.20,500.80,649.75
2024-08-02,7578.80,686.00,666.60,NaN,212.53,1655.40,301.65,854.55,NaN,NaN,...,325.20,1178.60,103.59,65.51,76.37,23259.45,22.34,1711.15,491.50,652.50
2024-08-05,7465.70,656.20,628.80,NaN,202.24,1553.05,291.65,795.85,NaN,NaN,...,312.00,1118.40,103.61,62.17,74.43,22542.45,22.25,1645.65,466.30,630.00
2024-08-06,7465.70,639.60,649.95,NaN,201.08,1517.45,287.55,772.45,NaN,NaN,...,301.10,1094.45,103.62,61.50,73.22,22443.30,21.98,1650.30,427.75,632.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-07-27,7327.50,989.20,3367.80,1214.9,169.43,2181.30,415.95,3536.80,3557.8,78.58,...,250.85,2283.10,115.19,80.63,76.41,23153.10,26.72,2525.30,1316.20,1599.80
2026-07-28,7243.50,999.20,3297.70,1202.0,168.84,2162.70,405.75,3457.80,3431.2,77.11,...,257.15,2192.20,115.19,80.20,76.08,23114.90,26.73,2576.90,1306.00,1643.10
2026-07-29,7310.50,1017.50,3306.20,1246.1,173.58,2171.50,405.15,3541.40,3425.0,77.47,...,257.60,2180.90,115.22,80.73,76.44,23352.60,27.08,2558.90,1343.40,1697.00
2026-07-30,7291.50,1008.80,3233.80,1240.9,172.72,2164.70,403.00,3530.30,3259.8,77.10,...,254.30,2132.90,115.24,79.26,76.50,23353.55,27.09,2562.20,1377.80,1655.00
2026-07-31,7468.50,1013.60,3166.90,1251.2,174.64,2204.30,411.65,3558.00,3387.8,78.28,...,256.20,2203.60,115.28,79.60,77.30,23438.95,27.22,2636.70,1395.20,1658.10

In [14]:
ticker_data['Ticker'].nunique()

25

In [15]:
weights

{'ABB': 0.034989129400632375,
 'ABSLAMC': 0.030507306936188788,
 'ACUTAAS': 0.03176813522719838,
 'ATHERENERG': 0.04268368228452352,
 'BANDHANBNK': 0.03322473854374172,
 'BHARATFORG': 0.04143545645636298,
 'BHEL': 0.0395747929406967,
 'BSE': 0.03828361446328757,
 'CPPLUS': 0.03582913988851138,
 'DEFENCE': 0.045956493329513126,
 'EMMVEE': 0.030419183813279863,
 'FINCABLES': 0.033121832799600986,
 'GVT&D': 0.03313315083666929,
 'HSCL': 0.040969582837156474,
 'J&KBANK': 0.03921314742778596,
 'JINDALSAW': 0.038165084557593376,
 'KIRLOSENG': 0.044216180098836835,
 'LIQUIDCASE': 0.10099844240340948,
 'MAHABANK': 0.03956797014941002,
 'NEXT50IETF': 0.05236891760174743,
 'PHARMABEES': 0.050320630075409954,
 'RRKABEL': 0.042291583084163566,
 'SYRMA': 0.03872372644169546,
 'WELCORP': 0.04223807840258489}

In [16]:
import pandas as pd
import numpy as np

def calculate_portfolio_beta_from_df(df, benchmark_name, weights_dict=None):
    """
    df: DataFrame with columns ['Ticker','Date','Close']
    benchmark_name: name used in the 'Ticker' column for your benchmark
    weights_dict: {'ABCAPITAL':0.1, 'BOSCHLTD':0.05, ...}
    """

    df['Date'] = pd.to_datetime(df['Date'])

    # Pivot → Date index, ticker columns
    price_df = df.pivot(index="Date", columns="Ticker", values="Close").sort_index()

    # keep only last 1 year (last 252 days)
    price_df = price_df.loc[price_df.index >= price_df.index.max() - pd.Timedelta(days=252)]
    # print(price_df)

    # Extract benchmark + stocks separately
    benchmark = price_df[benchmark_name]
    stock_prices = price_df.drop(columns=[benchmark_name])

    # daily returns
    returns = price_df.pct_change().dropna()
    stock_returns = returns.drop(columns=[benchmark_name])
    bench_ret = returns[benchmark_name]

    # weights: equal-weight if not given
    if weights_dict is None:
        n = stock_returns.shape[1]
        weights_dict = {col: 1/n for col in stock_returns.columns}

    weights = pd.Series(weights_dict).reindex(stock_returns.columns).fillna(0)

    # portfolio daily return
    portfolio_ret = (stock_returns * weights).sum(axis=1)

    # beta = Cov(portfolio, benchmark) / Var(benchmark)
    covariance = np.cov(portfolio_ret, bench_ret)[0][1]
    variance = np.var(bench_ret)

    beta = covariance / variance

    return beta, portfolio_ret, bench_ret

In [17]:
calculate_portfolio_beta_from_df(ticker_data, 'NIFTY 500', weights)[0]

np.float64(1.0005298998485606)

In [18]:
current_beta = pd.DataFrame({'Beta': [calculate_portfolio_beta_from_df(ticker_data, 'NIFTY 500', weights)[0]]})
current_beta.to_excel('momentum_ratios.xlsx', index=False)
current_beta

      Beta
0  1.00053