In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_excel("Trials\\Nifty_500_2025_Apr_20_stocks_results_GoldSilverDebt_buy&hold_returns.xlsx")
data

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Initial_Allocation,Selection_Date,Buy_Hold_Value,Buy_Price,Quantity,Real_Rank,Total_Portfolio_Value,Hedge_Segment
0,2023-04-03,154.00,154.90,152.00,153.80,2347046.0,0.0,ABCAPITAL,NaN,3.750000,2023-04-01,3.750000,153.80,0.024382,12.0,75.000000,NaN
1,2023-04-03,407.00,410.95,403.05,405.15,112564.0,0.0,ANANDRATHI,NaN,3.750000,2023-04-01,3.750000,405.15,0.009256,15.0,75.000000,NaN
2,2023-04-03,123.75,128.00,122.50,125.65,2365577.0,0.0,ANANTRAJ,NaN,3.750000,2023-04-01,3.750000,125.65,0.029845,19.0,75.000000,NaN
3,2023-04-03,169.10,170.25,168.10,169.20,16659059.0,0.0,BANKBARODA,NaN,3.750000,2023-04-01,3.750000,169.20,0.022163,7.0,75.000000,NaN
4,2023-04-03,75.00,76.45,74.10,75.95,8102076.0,0.0,BANKINDIA,NaN,3.750000,2023-04-01,3.750000,75.95,0.049375,3.0,75.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15943,2026-04-15,113.63,NaN,NaN,113.62,NaN,NaN,LIQUIDCASE,0.000176,39.128478,2026-03-01,39.353614,112.97,0.346362,NaN,65.051178,2026-03_onward
15944,2026-04-16,125.32,NaN,NaN,125.61,NaN,NaN,GOLDBEES,0.004398,28.422254,2026-03-01,25.810579,138.32,0.205482,NaN,65.167657,2026-03_onward
15945,2026-04-16,113.62,NaN,NaN,113.63,NaN,NaN,LIQUIDCASE,0.000088,39.128478,2026-03-01,39.357077,112.97,0.346362,NaN,65.167657,2026-03_onward
15946,2026-04-17,125.26,NaN,NaN,124.79,NaN,NaN,GOLDBEES,-0.006528,28.422254,2026-03-01,25.642084,138.32,0.205482,NaN,65.016480,2026-03_onward
15947,2026-04-17,113.68,NaN,NaN,113.68,NaN,NaN,LIQUIDCASE,0.000440,39.128478,2026-03-01,39.374395,112.97,0.346362,NaN,65.016480,2026-03_onward

In [3]:
# max_date_tickers = data[(data['Date'] == '2025-12-31')]
# max_date_tickers
max_date_tickers = data[(data['Date'] == data['Date'].max())]
max_date_tickers

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Initial_Allocation,Selection_Date,Buy_Hold_Value,Buy_Price,Quantity,Real_Rank,Total_Portfolio_Value,Hedge_Segment
15700,2026-04-17,148.86,149.47,147.73,148.47,1328896.0,0.0,BANKINDIA,-0.002620,8.551772,2026-04-01,9.268425,141.70,0.068095,11.0,205.015634,NaN
15701,2026-04-17,1855.80,1860.00,1821.00,1859.40,178234.0,0.0,BHARATFORG,0.001940,8.402194,2026-04-01,9.329416,1668.40,0.005103,5.0,205.015634,NaN
15702,2026-04-17,3455.00,3496.00,3425.00,3495.50,1258551.0,0.0,BSE,0.014158,7.999036,2026-04-01,10.419464,2867.60,0.002789,17.0,205.015634,NaN
15703,2026-04-17,432.80,435.45,430.50,435.10,1447456.0,0.0,COALINDIA,0.005430,7.999036,2026-04-01,7.726453,449.40,0.017799,18.0,205.015634,NaN
15704,2026-04-17,5043.00,5101.00,5011.20,5088.50,73247.0,0.0,CUMMINSIND,0.009984,7.999036,2026-04-01,9.044931,4609.10,0.001735,16.0,205.015634,NaN
15705,2026-04-17,284.95,286.80,282.85,285.50,737047.0,0.0,FEDERALBNK,0.003868,9.234863,2026-04-01,10.164046,267.60,0.035932,4.0,205.015634,NaN
15706,2026-04-17,1385.30,1409.90,1385.10,1396.00,82665.0,0.0,GESHIP,0.010569,7.999036,2026-04-01,7.893302,1460.10,0.005478,3.0,205.015634,NaN
15707,2026-04-17,1036.50,1036.85,1025.00,1028.55,938046.0,0.0,HINDALCO,-0.010915,11.162443,2026-04-01,12.981097,904.60,0.012630,9.0,205.015634,NaN
15708,2026-04-17,940.05,944.35,930.05,933.90,331575.0,0.0,INDIANB,-0.006542,9.502551,2026-04-01,10.493594,888.00,0.012150,13.0,205.015634,NaN
15709,2026-04-17,280.30,281.50,277.30,279.20,441913.0,0.0,KARURVYSYA,-0.005875,7.999036,2026-04-01,7.717107,291.85,0.027408,14.0,205.015634,NaN
15710,2026-04-17,71.80,72.99,71.24,72.45,5426132.0,0.0,MAHABANK,0.016842,7.866679,2026-04-01,9.293020,64.88,0.133222,15.0,205.015634,NaN
15711,2026-04-17,2884.00,2884.00,2848.00,2872.80,467021.0,0.0,MCX,0.003703,9.682503,2026-04-01,11.641372,2469.70,0.004587,6.0,205.015634,NaN
15712,2026-04-17,432.00,435.00,422.55,428.45,1905757.0,0.0,NATIONALUM,-0.009822,15.337917,2026-04-01,17.020281,399.45,0.039150,1.0,205.015634,NaN
15713,2026-04-17,6287.00,6318.00,6258.50,6309.00,14736.0,0.0,NAVINFLUOR,0.008472,7.999036,2026-04-01,8.189196,6034.00,0.001326,10.0,205.015634,NaN
15714,2026-04-17,283.40,285.00,282.20,283.30,2574725.0,0.0,ONGC,0.001945,7.999036,2026-04-01,7.961099,288.05,0.027770,20.0,205.015634,NaN
15715,2026-04-17,1067.00,1071.25,1060.00,1063.90,1252152.0,0.0,SBIN,-0.003045,10.471509,2026-04-01,11.374963,1017.80,0.010664,12.0,205.015634,NaN
15716,2026-04-17,1022.00,1033.80,1013.15,1032.10,837753.0,0.0,SHRIRAMFIN,0.009142,9.193246,2026-04-01,10.879886,900.55,0.010299,8.0,205.015634,NaN
15717,2026-04-17,1529.90,1542.80,1525.40,1539.10,60923.0,0.0,TORNTPOWER,0.011501,7.999036,2026-04-01,9.428179,1337.10,0.005982,19.0,205.015634,NaN
15718,2026-04-17,188.49,189.30,186.63,187.82,1699911.0,0.0,UNIONBANK,-0.003555,9.305649,2026-04-01,10.644257,171.64,0.060484,7.0,205.015634,NaN
15719,2026-04-17,782.85,785.00,772.40,779.60,2104291.0,0.0,VEDL,-0.004151,11.377146,2026-04-01,13.545545,677.20,0.017425,2.0,205.015634,NaN
15946,2026-04-17,125.26,NaN,NaN,124.79,NaN,NaN,GOLDBEES,-0.006528,28.422254,2026-03-01,25.642084,138.32,0.205482,NaN,65.016480,2026-03_onward
15947,2026-04-17,113.68,NaN,NaN,113.68,NaN,NaN,LIQUIDCASE,0.000440,39.128478,2026-03-01,39.374395,112.97,0.346362,NaN,65.016480,2026-03_onward

In [4]:
total_value = max_date_tickers['Buy_Hold_Value'].sum()

# Calculate weights
max_date_tickers['Weight'] = max_date_tickers['Buy_Hold_Value'] / total_value

# Format as percentage (optional)
max_date_tickers['Weight_Percent'] = max_date_tickers['Weight']

max_date_tickers

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Initial_Allocation,Selection_Date,Buy_Hold_Value,Buy_Price,Quantity,Real_Rank,Total_Portfolio_Value,Hedge_Segment,Weight,Weight_Percent
15700,2026-04-17,148.86,149.47,147.73,148.47,1328896.0,0.0,BANKINDIA,-0.002620,8.551772,2026-04-01,9.268425,141.70,0.068095,11.0,205.015634,NaN,0.034323,0.034323
15701,2026-04-17,1855.80,1860.00,1821.00,1859.40,178234.0,0.0,BHARATFORG,0.001940,8.402194,2026-04-01,9.329416,1668.40,0.005103,5.0,205.015634,NaN,0.034549,0.034549
15702,2026-04-17,3455.00,3496.00,3425.00,3495.50,1258551.0,0.0,BSE,0.014158,7.999036,2026-04-01,10.419464,2867.60,0.002789,17.0,205.015634,NaN,0.038586,0.038586
15703,2026-04-17,432.80,435.45,430.50,435.10,1447456.0,0.0,COALINDIA,0.005430,7.999036,2026-04-01,7.726453,449.40,0.017799,18.0,205.015634,NaN,0.028613,0.028613
15704,2026-04-17,5043.00,5101.00,5011.20,5088.50,73247.0,0.0,CUMMINSIND,0.009984,7.999036,2026-04-01,9.044931,4609.10,0.001735,16.0,205.015634,NaN,0.033496,0.033496
15705,2026-04-17,284.95,286.80,282.85,285.50,737047.0,0.0,FEDERALBNK,0.003868,9.234863,2026-04-01,10.164046,267.60,0.035932,4.0,205.015634,NaN,0.037640,0.037640
15706,2026-04-17,1385.30,1409.90,1385.10,1396.00,82665.0,0.0,GESHIP,0.010569,7.999036,2026-04-01,7.893302,1460.10,0.005478,3.0,205.015634,NaN,0.029231,0.029231
15707,2026-04-17,1036.50,1036.85,1025.00,1028.55,938046.0,0.0,HINDALCO,-0.010915,11.162443,2026-04-01,12.981097,904.60,0.012630,9.0,205.015634,NaN,0.048072,0.048072
15708,2026-04-17,940.05,944.35,930.05,933.90,331575.0,0.0,INDIANB,-0.006542,9.502551,2026-04-01,10.493594,888.00,0.012150,13.0,205.015634,NaN,0.038861,0.038861
15709,2026-04-17,280.30,281.50,277.30,279.20,441913.0,0.0,KARURVYSYA,-0.005875,7.999036,2026-04-01,7.717107,291.85,0.027408,14.0,205.015634,NaN,0.028578,0.028578
15710,2026-04-17,71.80,72.99,71.24,72.45,5426132.0,0.0,MAHABANK,0.016842,7.866679,2026-04-01,9.293020,64.88,0.133222,15.0,205.015634,NaN,0.034414,0.034414
15711,2026-04-17,2884.00,2884.00,2848.00,2872.80,467021.0,0.0,MCX,0.003703,9.682503,2026-04-01,11.641372,2469.70,0.004587,6.0,205.015634,NaN,0.043111,0.043111
15712,2026-04-17,432.00,435.00,422.55,428.45,1905757.0,0.0,NATIONALUM,-0.009822,15.337917,2026-04-01,17.020281,399.45,0.039150,1.0,205.015634,NaN,0.063031,0.063031
15713,2026-04-17,6287.00,6318.00,6258.50,6309.00,14736.0,0.0,NAVINFLUOR,0.008472,7.999036,2026-04-01,8.189196,6034.00,0.001326,10.0,205.015634,NaN,0.030327,0.030327
15714,2026-04-17,283.40,285.00,282.20,283.30,2574725.0,0.0,ONGC,0.001945,7.999036,2026-04-01,7.961099,288.05,0.027770,20.0,205.015634,NaN,0.029482,0.029482
15715,2026-04-17,1067.00,1071.25,1060.00,1063.90,1252152.0,0.0,SBIN,-0.003045,10.471509,2026-04-01,11.374963,1017.80,0.010664,12.0,205.015634,NaN,0.042124,0.042124
15716,2026-04-17,1022.00,1033.80,1013.15,1032.10,837753.0,0.0,SHRIRAMFIN,0.009142,9.193246,2026-04-01,10.879886,900.55,0.010299,8.0,205.015634,NaN,0.040291,0.040291
15717,2026-04-17,1529.90,1542.80,1525.40,1539.10,60923.0,0.0,TORNTPOWER,0.011501,7.999036,2026-04-01,9.428179,1337.10,0.005982,19.0,205.015634,NaN,0.034915,0.034915
15718,2026-04-17,188.49,189.30,186.63,187.82,1699911.0,0.0,UNIONBANK,-0.003555,9.305649,2026-04-01,10.644257,171.64,0.060484,7.0,205.015634,NaN,0.039418,0.039418
15719,2026-04-17,782.85,785.00,772.40,779.60,2104291.0,0.0,VEDL,-0.004151,11.377146,2026-04-01,13.545545,677.20,0.017425,2.0,205.015634,NaN,0.050163,0.050163
15946,2026-04-17,125.26,NaN,NaN,124.79,NaN,NaN,GOLDBEES,-0.006528,28.422254,2026-03-01,25.642084,138.32,0.205482,NaN,65.016480,2026-03_onward,0.094959,0.094959
15947,2026-04-17,113.68,NaN,NaN,113.68,NaN,NaN,LIQUIDCASE,0.000440,39.128478,2026-03-01,39.374395,112.97,0.346362,NaN,65.016480,2026-03_onward,0.145814,0.145814

In [5]:
# Convert to dictionary
weights = dict(zip(max_date_tickers['Ticker'], max_date_tickers['Weight']))

weights

{'BANKINDIA': 0.03432341931818798,
 'BHARATFORG': 0.0345492834098672,
 'BSE': 0.03858601716885124,
 'COALINDIA': 0.02861308851786088,
 'CUMMINSIND': 0.033495761883718514,
 'FEDERALBNK': 0.037640137287684075,
 'GESHIP': 0.02923097564733239,
 'HINDALCO': 0.048072418657459495,
 'INDIANB': 0.03886054070879534,
 'KARURVYSYA': 0.028578480475660775,
 'MAHABANK': 0.03441449897795906,
 'MCX': 0.043111063945965464,
 'NATIONALUM': 0.06303058088165608,
 'NAVINFLUOR': 0.030326747928349995,
 'ONGC': 0.029482046900300457,
 'SBIN': 0.042124482426146685,
 'SHRIRAMFIN': 0.040291082840116184,
 'TORNTPOWER': 0.03491503005942494,
 'UNIONBANK': 0.03941848439767312,
 'VEDL': 0.05016271954679406,
 'GOLDBEES': 0.09495938843236237,
 'LIQUIDCASE': 0.14581375058783386}

In [6]:
tickers = list(max_date_tickers['Ticker'].unique()) + ['NIFTY 500']
# tickers = [
#     "ABCAPITAL",
#     "AIIL",
#     "BOSCHLTD",
#     "DATAPATTNS",
#     "DELHIVERY",
#     "ETERNAL",
#     "GOLDBEES",
#     "GVT&D",
#     "HBLENGINE",
#     "HEROMOTOCO",
#     "HINDCOPPER",
#     "HYUNDAI",
#     "IIFL",
#     "INTELLECT",
#     "LAURUSLABS",
#     "LTF",
#     "MFSL",
#     "NETWEB",
#     "POLYCAB",
#     "SYRMA",
#     "TATAINVEST",
#     "NIFTY 500"
# ]

# tickers

In [7]:
len(tickers)

23

In [8]:
import os

import time
import logging
import pandas as pd
from truedata import TD_hist

def fetch_truedata_history(
    ticker_list: list,
    duration: str = '1 Y',
    bar_size: str = 'EOD',
    sleep_time: float = 0.1
) -> tuple[pd.DataFrame, list]:
    """
    Fetches historical data from TrueData for a list of tickers.

    Parameters
    ----------
    username : str
        TrueData username.
    password : str
        TrueData password.
    ticker_list : list
        List of ticker symbols to fetch data for.
    duration : str, optional
        Duration of data (e.g., '1 Y', '25 Y', etc.). Default is '1 Y'.
    bar_size : str, optional
        Bar size for data ('EOD', 'WEEK', etc.). Default is 'EOD'.
    sleep_time : float, optional
        Delay between API calls to avoid throttling. Default is 0.2 seconds.

    Returns
    -------
    final_df : pd.DataFrame
        Combined DataFrame of all tickers' historical data.
    error_list : list
        List of tickers that failed to fetch.
    """
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    username =  os.getenv("TRUEDATA_USERNAME")
    password = os.getenv("TRUEDATA_PASSWORD")
    # username =  'td105'
    # password = os.getenv("TRUEDATA_PASSWORD")
    # Initialize connection
    td_hist = TD_hist(username, password)
    df_list = []
    error_list = []
    for ticker in ticker_list:
        try:
            df = td_hist.get_historic_data([ticker], duration=duration, bar_size=bar_size)

            df['Ticker'] = ticker
            df = df.rename(columns={
                'timestamp': 'Date',
                'high': 'High',
                'low': 'Low',
                'close': 'Close',
                'open': 'Open'
            })

            df_list.append(df)
            logging.info(f"Fetched data for {ticker} ({len(df)} rows).")
            time.sleep(sleep_time)

        except Exception as e:
            logging.error(f"Failed to fetch data for {ticker}: {e}")
            error_list.append(ticker)

    final_df = pd.concat(df_list, ignore_index=True) if df_list else pd.DataFrame()
    return final_df, error_list

In [9]:
ticker_data = fetch_truedata_history(
        ticker_list = tickers,
        duration = '2 Y',
        bar_size = 'EOD',
        sleep_time= 0.1
    )[0][['Ticker','Date', 'Close']]
ticker_data

(2026-04-17 09:56:20,058) WARNING :: Connected successfully to TrueData Historical Data Service...  (PID:2640 Thread:5548)
2026-04-17 09:56:20,058 - WARNING - Connected successfully to TrueData Historical Data Service...
2026-04-17 09:56:20,829 - INFO - Fetched data for BANKINDIA (496 rows).
2026-04-17 09:56:21,315 - INFO - Fetched data for BHARATFORG (496 rows).
2026-04-17 09:56:21,802 - INFO - Fetched data for BSE (496 rows).
2026-04-17 09:56:22,305 - INFO - Fetched data for COALINDIA (496 rows).
2026-04-17 09:56:22,799 - INFO - Fetched data for CUMMINSIND (496 rows).
2026-04-17 09:56:23,286 - INFO - Fetched data for FEDERALBNK (496 rows).
2026-04-17 09:56:23,764 - INFO - Fetched data for GESHIP (496 rows).
2026-04-17 09:56:24,309 - INFO - Fetched data for HINDALCO (496 rows).
2026-04-17 09:56:24,832 - INFO - Fetched data for INDIANB (496 rows).
2026-04-17 09:56:25,324 - INFO - Fetched data for KARURVYSYA (496 rows).
2026-04-17 09:56:26,439 - INFO - Fetched data for MAHABANK (496 rows).
2026-04-17 09:56:26,918 - INFO - Fetched data for MCX (496 rows).
2026-04-17 09:56:27,393 - INFO - Fetched data for NATIONALUM (496 rows).
2026-04-17 09:56:27,874 - INFO - Fetched data for NAVINFLUOR (496 rows).
2026-04-17 09:56:28,410 - INFO - Fetched data for ONGC (496 rows).
2026-04-17 09:56:28,891 - INFO - Fetched data for SBIN (496 rows).
2026-04-17 09:56:29,386 - INFO - Fetched data for SHRIRAMFIN (496 rows).
2026-04-17 09:56:29,863 - INFO - Fetched data for TORNTPOWER (496 rows).
2026-04-17 09:56:30,360 - INFO - Fetched data for UNIONBANK (496 rows).
2026-04-17 09:56:30,919 - INFO - Fetched data for VEDL (496 rows).
2026-04-17 09:56:31,407 - INFO - Fetched data for GOLDBEES (496 rows).
2026-04-17 09:56:31,887 - INFO - Fetched data for LIQUIDCASE (496 rows).
2026-04-17 09:56:32,387 - INFO - Fetched data for NIFTY 500 (496 rows).

          Ticker       Date     Close
0      BANKINDIA 2024-04-18    137.80
1      BANKINDIA 2024-04-19    135.75
2      BANKINDIA 2024-04-22    141.25
3      BANKINDIA 2024-04-23    144.30
4      BANKINDIA 2024-04-24    144.45
...          ...        ...       ...
11403  NIFTY 500 2026-04-10  22346.75
11404  NIFTY 500 2026-04-13  22179.05
11405  NIFTY 500 2026-04-15  22595.55
11406  NIFTY 500 2026-04-16  22656.30
11407  NIFTY 500 2026-04-17  22724.20

[11408 rows x 3 columns]

In [10]:
ticker_data[ticker_data.duplicated(subset=['Ticker', 'Date'])]

Empty DataFrame
Columns: [Ticker, Date, Close]
Index: []

In [11]:
ticker_data = ticker_data.drop_duplicates(subset=['Ticker', 'Date'])

In [12]:
# ticker_data[ticker_data['Ticker'] == 'MOGSEC'].to_excel('MOGSEC.xlsx', index=False)

In [13]:
ticker_data.pivot(index="Date", columns="Ticker", values="Close").sort_index()

Ticker,BANKINDIA,BHARATFORG,BSE,COALINDIA,CUMMINSIND,FEDERALBNK,GESHIP,GOLDBEES,HINDALCO,INDIANB,...,MCX,NATIONALUM,NAVINFLUOR,NIFTY 500,ONGC,SBIN,SHRIRAMFIN,TORNTPOWER,UNIONBANK,VEDL
Date,,,,,,,,,,,,,,,,,,,,,
2024-04-18,137.80,1186.20,927.05,438.60,3124.05,152.15,1022.50,61.96,612.80,511.25,...,778.10,181.35,3228.85,20324.70,274.15,744.80,474.30,1511.35,142.55,388.50
2024-04-19,135.75,1193.10,922.85,435.30,3038.25,151.85,1008.90,62.24,614.75,512.15,...,758.45,184.80,3222.65,20385.20,275.25,750.45,473.30,1501.15,140.70,385.95
2024-04-22,141.25,1204.50,950.45,442.95,3128.10,153.50,1031.05,61.74,618.55,520.85,...,780.65,185.45,3278.60,20574.85,276.80,766.10,484.95,1476.60,150.60,381.00
2024-04-23,144.30,1206.55,1066.60,440.95,3159.15,153.75,1020.05,60.25,611.80,516.00,...,804.40,183.35,3374.15,20652.65,276.80,773.00,485.40,1504.55,146.90,377.05
2024-04-24,144.45,1222.00,1043.30,443.85,3244.30,153.60,1068.00,60.73,636.10,509.95,...,767.90,188.00,3283.50,20730.65,279.35,773.10,492.20,1515.10,147.10,383.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-10,147.93,1798.80,3281.20,434.10,5138.70,291.70,1372.90,123.49,992.10,967.75,...,2669.40,417.00,6181.00,22346.75,286.50,1066.70,1027.55,1471.80,189.03,745.15
2026-04-13,144.97,1801.30,3303.60,435.10,4991.40,288.20,1335.30,123.76,978.25,966.50,...,2765.60,418.05,6238.00,22179.05,287.55,1063.55,1004.10,1473.60,184.68,752.55
2026-04-15,147.70,1831.60,3390.70,435.80,5003.40,286.85,1400.40,125.06,1011.45,946.00,...,2851.10,423.90,6222.50,22595.55,287.60,1071.50,1020.95,1506.70,188.71,766.05
2026-04-16,148.86,1855.80,3446.70,432.75,5038.20,284.40,1381.40,125.61,1039.90,940.05,...,2862.20,432.70,6256.00,22656.30,282.75,1067.15,1022.75,1521.60,188.49,782.85
2026-04-17,148.37,1861.00,3498.60,435.15,5099.00,285.75,1394.30,124.82,1028.10,935.85,...,2867.20,428.00,6301.00,22724.20,283.30,1063.90,1031.65,1539.50,187.75,779.15

In [14]:
ticker_data['Ticker'].nunique()

23

In [15]:
weights

{'BANKINDIA': 0.03432341931818798,
 'BHARATFORG': 0.0345492834098672,
 'BSE': 0.03858601716885124,
 'COALINDIA': 0.02861308851786088,
 'CUMMINSIND': 0.033495761883718514,
 'FEDERALBNK': 0.037640137287684075,
 'GESHIP': 0.02923097564733239,
 'HINDALCO': 0.048072418657459495,
 'INDIANB': 0.03886054070879534,
 'KARURVYSYA': 0.028578480475660775,
 'MAHABANK': 0.03441449897795906,
 'MCX': 0.043111063945965464,
 'NATIONALUM': 0.06303058088165608,
 'NAVINFLUOR': 0.030326747928349995,
 'ONGC': 0.029482046900300457,
 'SBIN': 0.042124482426146685,
 'SHRIRAMFIN': 0.040291082840116184,
 'TORNTPOWER': 0.03491503005942494,
 'UNIONBANK': 0.03941848439767312,
 'VEDL': 0.05016271954679406,
 'GOLDBEES': 0.09495938843236237,
 'LIQUIDCASE': 0.14581375058783386}

In [16]:
import pandas as pd
import numpy as np

def calculate_portfolio_beta_from_df(df, benchmark_name, weights_dict=None):
    """
    df: DataFrame with columns ['Ticker','Date','Close']
    benchmark_name: name used in the 'Ticker' column for your benchmark
    weights_dict: {'ABCAPITAL':0.1, 'BOSCHLTD':0.05, ...}
    """

    df['Date'] = pd.to_datetime(df['Date'])

    # Pivot → Date index, ticker columns
    price_df = df.pivot(index="Date", columns="Ticker", values="Close").sort_index()

    # keep only last 1 year (last 252 days)
    price_df = price_df.loc[price_df.index >= price_df.index.max() - pd.Timedelta(days=252)]
    # print(price_df)

    # Extract benchmark + stocks separately
    benchmark = price_df[benchmark_name]
    stock_prices = price_df.drop(columns=[benchmark_name])

    # daily returns
    returns = price_df.pct_change().dropna()
    stock_returns = returns.drop(columns=[benchmark_name])
    bench_ret = returns[benchmark_name]

    # weights: equal-weight if not given
    if weights_dict is None:
        n = stock_returns.shape[1]
        weights_dict = {col: 1/n for col in stock_returns.columns}

    weights = pd.Series(weights_dict).reindex(stock_returns.columns).fillna(0)

    # portfolio daily return
    portfolio_ret = (stock_returns * weights).sum(axis=1)

    # beta = Cov(portfolio, benchmark) / Var(benchmark)
    covariance = np.cov(portfolio_ret, bench_ret)[0][1]
    variance = np.var(bench_ret)

    beta = covariance / variance

    return beta, portfolio_ret, bench_ret

In [17]:
calculate_portfolio_beta_from_df(ticker_data, 'NIFTY 500', weights)[0]

np.float64(0.9599277727259348)

In [18]:
current_beta = pd.DataFrame({'Beta': [calculate_portfolio_beta_from_df(ticker_data, 'NIFTY 500', weights)[0]]})
current_beta.to_excel('momentum_ratios.xlsx', index=False)
current_beta

       Beta
0  0.959928